PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO turmas (id, nome) VALUES (1, 'Backend - Manhã');
INSERT OR IGNORE INTO turmas (id, nome) VALUES (2, 'Banco de Dados - Manhã');
INSERT OR IGNORE INTO turmas (id, nome) VALUES (3, 'Programação - Manhã');
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (1, 'Amanda Alves', 1);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (2, 'Beatriz Costa', 1);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (3, 'Carlos Eduardo', 1);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (4, 'Daniel Silva', 1);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (5, 'Eduarda Lima', 2);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (6, 'Felipe Rocha', 2);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (7, 'Gabriela Souza', 2);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (8, 'Henrique Martins', 2);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (9, 'Isabela Santos', 3);
INSERT OR IGNORE INTO alunos (id, nome, turma_id) VALUES (10, 'João Pedro', 3);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (1, '20260001', 1);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (2, '20260002', 2);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (3, '20260003', 3);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (4, '20260004', 4);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (5, '20260005', 5);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (6, '20260006', 6);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (7, '20260007', 7);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (8, '20260008', 8);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (9, '20260009', 9);
INSERT OR IGNORE INTO carteirinhas (id, numero, aluno_id) VALUES (10, '20260010', 10);
INSERT OR IGNORE INTO disciplinas (id, nome) VALUES (1, 'Banco de Dados');
INSERT OR IGNORE INTO disciplinas (id, nome) VALUES (2, 'Programação Backend');
INSERT OR IGNORE INTO disciplinas (id, nome) VALUES (3, 'Modelagem de Dados');
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (1, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (1, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (2, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (2, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (3, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (3, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (4, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (4, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (5, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (5, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (6, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (6, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (7, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (7, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (8, 2);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (8, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (9, 3);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (9, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (10, 1);
INSERT OR IGNORE INTO aluno_disciplina (aluno_id, disciplina_id) VALUES (10, 2);
